jobs:

- name: setBalanceBase
  job:
    set:
      val: 5

- name: deployContract
  job:
    deploy:
      contract: idi.sol
      wait: true

- name: setBalance
  job:
    call:
      destination: $deployContract
      data: set $setBalanceBase
      wait: true

- name: queryOwner
  job:
    query-contract:
      destination: $deployContract
      data: getOwner

- name: queryBalance
  job:
    query-contract:
      destination: $deployContract
      data: getBalance

- name: assertOwner
  job:
    assert:
      key: $queryOwner
      relation: ne
      val: 0

- name: assertBalance
  job:
    assert:
      key: $queryBalance
      relation: eq
      val: $setBalanceBase
