jobs:

- name: TaskManager
  job:
    deploy:
      contract: TaskManager.sol
      instance: all
      wait: true

- name: UserManager
  job:
    deploy:
      contract: UserManager.sol
      instance: all
      wait: true
